[build]
  command = "npm run build"
  publish = ".netlify/output"          # plugin will generate this
  functions = ".netlify/functions"    # SSR/API routes

[[plugins]]
  package = "@netlify/plugin-nextjs"